[env:esp32-s3-devkitc-1]
; platform = espressif32
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
;upload_port = /dev/ttyACM1
;monitor_port = /dev/ttyACM1
; upload_port = /dev/ttyUSB0
; monitor_port = /dev/ttyUSB0

upload_protocol = espota
upload_port = esp32s3.local
monitor_port = socket://esp32s3.local:23


lib_deps =
    marian-craciunescu/ESP32Ping @ ^1.7
    jandrassy/TelnetStream @ ^1.3.0
    tanakamasayuki/EspUsbHost @ ^2.0.0


custom_sdkconfig = 
    CONFIG_USB_HOST_CONTROL_TRANSFER_MAX_SIZE=512
    CONFIG_ESPTOOLPY_FLASHSIZE_8MB=y

custom_component_remove = 
    espressif/esp_insights
    espressif/esp_diagnostics
    espressif/esp_rainmaker
    espressif/rmaker_common
    espressif/esp_diag_data_store

build_unflags = 
    -std=gnu++11

build_flags = 
    -std=gnu++17
    -D CONFIG_USB_HOST_CONTROL_TRANSFER_MAX_SIZE=512
    -I"${platformio.packages_dir}/framework-arduinoespressif32-libs/esp32s3/include/arduino_tinyusb/tinyusb/src"
    -I"${platformio.packages_dir}/framework-arduinoespressif32-libs/esp32s3/include/arduino_tinyusb/include"
    -D CORE_DEBUG_LEVEL=4
